const mappings = {
  BEEF: 'NAUDANPAISTI',
  CHICKEN: 'KANA',
  VEGETARIAN: 'KASVISPIHVI/PYÖRYKKÄ, PAISTETTU',
  SALMON: 'KIRJOLOHIFILEE, UUNISSA',
  PORK: 'PORSAANFILEE, ULKOFILEE',
  SHELLFISH: 'KATKARAPU',
  WHITE_FISH: 'TURSKA, KEITETTY, SUOLATON'
};

module.exports = {
  mappings
};